### ISSUE TITLE
Actually load and return a model?

### ISSUE THREAD

**Issue by turian** [maxrmorrison/torchcrepe#13]
I am trying to implement a torchcrepe baseline for the HEAR 2021 NeurIPS competition. You can see a wav2vec2 example here: https://github.com/neuralaudio/hear-baseline/blob/main/hearbaseline/wav2vec2.py

However, torchcrepe.load.model is prefer weird. It just kinda loads the model into some global explicit state dict?

Is there a way actually to simple load the pytorch model and pass it around? The current implementation is pretty opinionated and hard to build on

**Comment by maxrmorrison** [comment]
I would consider `torchcrepe.load.model` private. `torchcrepe.load.model` is only for preloading the model used by the inference script. It's an alternative to using a class-based interface, but without requiring users to perform explicit initialization. That's also why it's not in the documentation. It's intentionally hard to build on because it messes with private state.

But, if you were trying to directly access the model, I guess I don't see why you can't pass around the model that's been preloaded?
```
torchcrepe.load.model('cuda:0')
model = torchcrepe.infer.model
# Do stuff with model
```

You can also just make your own loader that doesn't perform preloading. You can use the first few lines of the `torchcrepe.load.model` for reference.
