### ISSUE TITLE
Predict over batch size greater than 1?

### ISSUE THREAD

**Issue by turian** [maxrmorrison/torchcrepe#34]
It appears that you can't really predict over audio with batch size greater than 1?

```
import torch
import torchcrepe

audio = torch.rand((2, 48000), device=device)

# Here we'll use a 5 millisecond hop length
hop_length = 16000 / 200

# Provide a sensible frequency range for your domain (upper limit is 2006 Hz)
# This would be a reasonable range for speech
fmin = 50
fmax = 550

# Select a model capacity--one of "tiny" or "full"
model = 'full'

# Pick a batch size that doesn't cause memory errors on your gpu
batch_size = 2048

# Compute pitch using first gpu
pitch = torchcrepe.predict(audio,
                           16000,
                           hop_length,
                           fmin,
                           fmax,
                           model,
                           batch_size=batch_size,
                           return_periodicity=True
           )
```

gives:

```
  File "/opt/miniconda3/lib/python3.9/site-packages/torchcrepe/core.py", line 117, in predict
    for frames in generator:
  File "/opt/miniconda3/lib/python3.9/site-packages/torchcrepe/core.py", line 682, in preprocess
    frames = torch.nn.functional.unfold(
  File "/opt/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 4756, in unfold
    return torch._C._nn.im2col(input, _pair(kernel_size), _pair(dilation), _pair(padding), _pair(stride))
TypeError: im2col(): argument 'stride' failed to unpack the object at pos 2 with error "type must be tuple of ints,but got float"
```

(This is even though I have 16000 Hz audio, which skips the resample line which assumes 1-batch audio.)

**Comment by maxrmorrison** [comment]
Batching occurs internally over frames (1024 samples at 16 kHz for the specified hopsize). So there's no speed-up to be had for a larger input batch size. But you can get more speed via async load/save and careful concatenation. See, e.g., `penn.from_files_to_files` for `num_workers > 0` https://github.com/interactiveaudiolab/penn/blob/82260676a2594d98ce7ba94ff1fcef2dc549aa13/penn/core.py#L191

But note that `penn` uses a different decoding by default

**Comment by turian** [comment]
It's not about speed. It's that it's a typical ML workflow to have all your examples batched in training and validation loops.

I understand that being doing something tricky can avoid unbatching. I'm just trying to keep my pipeline simplify and idiomatic.

**Comment by maxrmorrison** [comment]
I think we have a different design ideology here. That idiom exists due to speedups: [CUDNN only performs tensor core operations in batch sizes that are multiples of eight, and pads if you don't have a multiple of eight](https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#tensor_ops). Pitch estimation is a weird case relative to nearly all other audio tasks, in that one frame is a batch--not one audio file. In my opinion, adhering strictly to that batched ML idiom requires the user to chunk their own audio into frames and call `torchcrepe.infer` directly.

You're welcome to submit a pull request that modifies `torchcrepe.from_audio` to run a for loop over batches (or channels in the case of multichannel audio)--and I do think people will benefit from it. But that will also mask the fact that idiomatic batching in the traditional way we think about audio problems just isn't happening here. And users will then believe that frame [0] of each batch will be processed first, which isn't the case. Also, some operations like resampling and decoding break gradients, which would subvert expectations. And, users will believe that they need to stack multiple audio files of potentially different lengths--causing padding overhead--in order to utilize batching.

So I think there are pros and cons for each, and the crux of the issue is that pitch estimation does not behave in an idiomatic way relative to other audio tasks.

**Comment by turian** [comment]
@maxrmorrison Okay I understand your perspective. I think it depends upon the intended user. Some just want pitch for a track. Others are working with pre-batched audio within some pipeline. I can be both, but usually the latter
