### ISSUE TITLE
"RuntimeError: "im2col_out_cpu" not implemented for 'Int'" when trying to run "Computing pitch and periodicity from audio" usage example.

### ISSUE THREAD

**Issue by Looki2000** [maxrmorrison/torchcrepe#36]

**Comment by maxrmorrison** [comment]
This sounds like the dtype of the audio is an integer instead of a float. I presume this has to do with loading the audio in a different manner than specified in the usage example—which returns floating-point values in [-1, 1]. I've also recently updated the loading to use `torchaudio` instead of `wavfile`. Either way, this should not be an issue in release 0.0.23.
